version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: taskmanager_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    container_name: taskmanager_backend
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./apps/backend:/app
      - /app/node_modules  # prevent host node_modules overwrite
    env_file:
      - ./apps/backend/.env
    depends_on:
      - postgres
    command: npm run dev

  frontend:
    build:
      context: ./apps/frontend
    ports:
      - "5173:5173"
    volumes:
      - ./apps/frontend:/app
      -  /app/node_modules
    env_file:
      - ./apps/frontend/.env
    environment:
      - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
      - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
      - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm run dev

volumes:
  pgdata:
