version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: taskmanager_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    container_name: taskmanager_backend
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./apps/backend:/app
      - /app/node_modules  # prevent host node_modules overwrite
    env_file:
      - ./apps/backend/.env
    depends_on:
      - postgres
    command: npm run dev

volumes:
  pgdata:
